name: fetchtrue
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Widgets
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^31.1.18
  dotted_border:
  scratcher: ^2.5.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0
  youtube_player_flutter: ^9.1.1


#  State Management & Utilities
  flutter_bloc: ^9.1.0
  provider: ^6.1.5
  equatable: ^2.0.7
  intl: ^0.20.2
  go_router: ^16.2.1

#  Device Information & System Utilities
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_email_sender: ^7.0.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1

  # File & PDF Handling
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  video_player: ^2.8.2
  india_state_city_picker: ^0.0.3

  # Networking & Web
  dio: ^5.8.0+1
  flutter_inappwebview: ^6.1.5
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  # http: ^1.4.0   # remove if not needed


  # Firebase Services
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
#  firebase_messaging: ^16.0.1


dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/fetch_true_icon.jpg"
  min_sdk_android: 23

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/auth/
    - assets/image/
    - assets/icon/
    - assets/package/
    - assets/lead/
    - assets/academy/
