// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QJJA6Ip6PqSP9f28Q92qQ9Jxb2ubWNU',
    appId: '1:1041578063290:web:5c7444883b66ce8f529983',
    messagingSenderId: '1041578063290',
    projectId: 'fetchtrue-2025',
    authDomain: 'fetchtrue-2025.firebaseapp.com',
    storageBucket: 'fetchtrue-2025.firebasestorage.app',
    measurementId: 'G-BY9Q64X0Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4P_Pf34I0keVooS6gsFeMvY-1kycK68c',
    appId: '1:1041578063290:android:e001eebb354a634e529983',
    messagingSenderId: '1041578063290',
    projectId: 'fetchtrue-2025',
    storageBucket: 'fetchtrue-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wgnvxy6rjRw_4US0HT347COvFmq97Dg',
    appId: '1:1041578063290:ios:6fbcd8f4fb4ccc77529983',
    messagingSenderId: '1041578063290',
    projectId: 'fetchtrue-2025',
    storageBucket: 'fetchtrue-2025.firebasestorage.app',
    iosBundleId: 'com.example.bizbooster2x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wgnvxy6rjRw_4US0HT347COvFmq97Dg',
    appId: '1:1041578063290:ios:6fbcd8f4fb4ccc77529983',
    messagingSenderId: '1041578063290',
    projectId: 'fetchtrue-2025',
    storageBucket: 'fetchtrue-2025.firebasestorage.app',
    iosBundleId: 'com.example.bizbooster2x',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QJJA6Ip6PqSP9f28Q92qQ9Jxb2ubWNU',
    appId: '1:1041578063290:web:7dddd1e75cf000cf529983',
    messagingSenderId: '1041578063290',
    projectId: 'fetchtrue-2025',
    authDomain: 'fetchtrue-2025.firebaseapp.com',
    storageBucket: 'fetchtrue-2025.firebasestorage.app',
    measurementId: 'G-0VN2DBF5NQ',
  );
}
